// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAczettPhczWWjJ1VrTTOx7qEkREDEQlZc',
    appId: '1:554453211095:web:c9a3db108782e06d189d92',
    messagingSenderId: '554453211095',
    projectId: 'makehappy-3f0bf',
    authDomain: 'makehappy-3f0bf.firebaseapp.com',
    storageBucket: 'makehappy-3f0bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOSD4Oa8SzKi176iy3iyN2dW_Quew6Vik',
    appId: '1:554453211095:android:2368326cb9edd37c189d92',
    messagingSenderId: '554453211095',
    projectId: 'makehappy-3f0bf',
    storageBucket: 'makehappy-3f0bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtdnNwofNBp1gunV5AxUvGTqvZYOd7f0w',
    appId: '1:554453211095:ios:83e15efe6c3f4125189d92',
    messagingSenderId: '554453211095',
    projectId: 'makehappy-3f0bf',
    storageBucket: 'makehappy-3f0bf.appspot.com',
    iosClientId: '554453211095-eqmu6fmgksfkkpfasdl7qpbehmgmhg0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeHappy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtdnNwofNBp1gunV5AxUvGTqvZYOd7f0w',
    appId: '1:554453211095:ios:83e15efe6c3f4125189d92',
    messagingSenderId: '554453211095',
    projectId: 'makehappy-3f0bf',
    storageBucket: 'makehappy-3f0bf.appspot.com',
    iosClientId: '554453211095-eqmu6fmgksfkkpfasdl7qpbehmgmhg0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeHappy',
  );
}
